### ISSUE TITLE
Connection closed even when commands are not finished

### ISSUE THREAD

**Issue by jorenvh** [LaravelCollective/remote#28] opened 2016-07-08 07:27 UTC
Hi,

The moment I hit route x I process some data and ssh into my server and run for example npm install. I noticed that I hit the success part of my function and my script is done according to laravel. But when I check the server there is no node modules folder. If I check the processes running with ps aux on my server I still see my commands being processed/executed/

Is there a way to tell the package to not close the connection until the commands are finished? (the command is executed in a queued job so timeouts won’t be a problem).

Joren

**Comment by wenzhu191** [comment] 2016-07-11 13:18
HI,It is good extension for laravel framework
but,when I use in controller  it not work!  
first I define a task by method SSH::define then  called SHH::task method to run the task It not work
by debugger I found tasks[$task] which is the property of Connect is empty.
Is that where I was wrong ?    Look forward to your reply,thanks
by leechao

**Comment by jorenvh** [comment] 2016-07-11 13:21
@wenzhu191 What peace of your question is related with my issue above? Please make a new issue for your specific question.

**Comment by ydhamija96** [comment] 2016-08-17 14:29
Same problem here.

**Comment by dmyers** [comment] 2016-09-05 07:33
Yeah I'm having the same issue upgrading from Laravel 4.2 + PHP 5.x to Laravel 5.3 + PHP 7 and I'm not sure the cause, but the code below is what I'm using and my queue doesn't time out, but for some reason the run command exits while I'm logging a long running process.

```php
SSH::run('process.sh', function($msg) { logger($msg); });
```

Any thoughts @adamgoose?

**Comment by dmyers** [comment] 2016-09-05 08:10
My guess so far is that phpseclib made a backwards incompatible change. I found this issue: https://github.com/phpseclib/phpseclib/issues/775 which lines up with my attempts to disable the timeout by passing false or 0 as the timeout and neither work correctly.

My only solution so far is to set the timeout to a large integer and hope the phpseclib package restores the original ability to properly disable the timeout.

**Comment by mlantz** [comment] 2017-05-19 08:47
This seems like its an issue directly related to phpseclib/phpseclib#775 as @dmyers mentioned. I'm closing this for now. If an incompatibility arises we please post a new issue. Thanks.

**Closed by mlantz** 2017-05-19 08:47 UTC
